from datetime import datetime

from weather import get_weather
from quote import get_quote
from news import get_news


def build_summary():

    weather = get_weather()
    quote = get_quote()
    news = get_news()

    today = datetime.now().strftime("%d-%m-%Y")

    summary = f"""
================================
      DAILY PULSE REPORT
================================

Date: {today}

WEATHER
--------
{weather}

NEWS
--------
{news}

QUOTE OF THE DAY
--------
{quote}

================================
Generated by Pulse Bot
================================
"""

    return summary


summary = build_summary()

with open("daily_summary.txt", "w", encoding="utf-8") as file:
    file.write(summary)

print(summary)
print("Pulse Bot executed successfully.")